<?php

/**
 * Implements hook_menu().
 * @author djik
 * @return array
 */
function dw_tools_menu() {
	
	variable_set('djikweb_variables','0');	
	
	$items['admin/config/development/djikweb/page'] = array(
  		'title' 				=> t('Blank page'),
  		'description' 			=> t('Blank page to test methods'),
    	'page callback' 		=> 'dw_tools_testing_page',
    	'access arguments' 		=> array('administer content types'),
  		'file' 					=> 'dw_tools.pages.inc',
  		'menu_name' 			=> 'djikweb',
	    'type' => MENU_NORMAL_ITEM,
  		'weight'				=> 0,
  	);
		
	$items['djikweb/generate/install/mysql'] = array(
	  		'title' 				=> t('Creation script generator of database'),
	  		'description' 			=> '',
	  		'page callback' 		=> 'drupal_get_form',
	  		'page arguments' 		=> array('dw_tools_generate_install_mysql'),
	  		'access callback' 		=> TRUE,
	  		'menu_name' 			=> 'djikweb',
	        'file' 					=> 'dw_tools.pages.inc',
	  		'weight'				=> 2,
	);
	
	$items['djikweb/generate/password'] = array(
	    'title' 				=> t('Crypt a password'),
	    'description' 			=> '',
	    'page callback' 		=> 'drupal_get_form', 
	    'page arguments' 		=> array('dw_tools_generate_password'),
	    'access callback' 		=> TRUE,
	    'menu_name' 			=> 'djikweb',
	    'file' 					=> 'dw_tools.pages.inc',
	    'weight'				=> 3,
	);

  	return $items;
}



